export { default as HomePage } from './HomePage'
export { default as ServicesPage } from './ServicesPage'
export { default as ProductsPage } from './ProductsPage'
export { default as GalleryPage } from './GalleryPage'
export { default as AboutPage } from './AboutPage'
export { default as ContactPage } from './ContactPage'
